// <auto-generated />
using System;
using BusX.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusX.Infrastructure.Migrations
{
    [DbContext(typeof(BusXDbContext))]
    [Migration("20251130101455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("BusX.Core.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalEstimate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromStationId");

                    b.HasIndex("ToStationId");

                    b.ToTable("Journeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalEstimate = new DateTime(2025, 12, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            BasePrice = 500m,
                            CreatedAt = new DateTime(2025, 11, 30, 10, 14, 55, 8, DateTimeKind.Utc).AddTicks(503),
                            Departure = new DateTime(2025, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            FromStationId = 1,
                            ProviderName = "ProviderA",
                            ToStationId = 2
                        },
                        new
                        {
                            Id = 2,
                            ArrivalEstimate = new DateTime(2025, 12, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            BasePrice = 450m,
                            CreatedAt = new DateTime(2025, 11, 30, 10, 14, 55, 8, DateTimeKind.Utc).AddTicks(523),
                            Departure = new DateTime(2025, 12, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            FromStationId = 1,
                            ProviderName = "ProviderB",
                            ToStationId = 2
                        });
                });

            modelBuilder.Entity("BusX.Core.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenderLock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JourneyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("BusX.Core.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Istanbul",
                            CreatedAt = new DateTime(2025, 11, 30, 10, 14, 55, 8, DateTimeKind.Utc).AddTicks(367),
                            Name = "Esenler Otogarı"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ankara",
                            CreatedAt = new DateTime(2025, 11, 30, 10, 14, 55, 8, DateTimeKind.Utc).AddTicks(370),
                            Name = "AŞTİ"
                        },
                        new
                        {
                            Id = 3,
                            City = "Izmir",
                            CreatedAt = new DateTime(2025, 11, 30, 10, 14, 55, 8, DateTimeKind.Utc).AddTicks(371),
                            Name = "İzotaş"
                        });
                });

            modelBuilder.Entity("BusX.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JourneyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassengerTc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pnr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BusX.Core.Entities.Journey", b =>
                {
                    b.HasOne("BusX.Core.Entities.Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusX.Core.Entities.Station", "ToStation")
                        .WithMany()
                        .HasForeignKey("ToStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStation");

                    b.Navigation("ToStation");
                });

            modelBuilder.Entity("BusX.Core.Entities.Seat", b =>
                {
                    b.HasOne("BusX.Core.Entities.Journey", null)
                        .WithMany("Seats")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusX.Core.Entities.Journey", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
